apiVersion: v1
kind: Service
metadata:
  name: national-tsa
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: national-tsa
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
